---

- name: check if custom groups exists
  group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ custom_groups }}"

- name: check user groups
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | select('in', custom_groups | map(attribute='name') | list) | join(',') }}"
  with_items: "{{ users }}"

- name: manage users and groups
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
    password: "{{ item.password | password_hash('sha512') }}"
    groups: "{{ item.groups }}"
  with_items: "{{ users }}"

- name: remove home directory if user state is absent
  file:
    path: "/home/{{ item.name }}"
    state: absent
  when: item.state == 'absent'
  with_items: "{{ users }}"

- name: add ssh public key
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
  when: item.ssh_key is defined and item.state == 'present'
  with_items: "{{ users }}"
