---

- name: install nginx
  apt:
    name: nginx
    state: present

- name: copy vhost nginx config
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - reload nginx

- name: copy nginx config
  template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
